all: admissible gch

admissible:
	drawio --export --embed-diagram recursive-h.drawio -o recursive-h.svg
	drawio --export --embed-diagram recursive-h.drawio -o recursive-h.pdf
gch:
	drawio --export --embed-diagram gch.drawio -o gch-proof.svg
	drawio --export --embed-diagram gch.drawio -o gch-proof.pdf
